"""Change hashed password type to bytes

Revision ID: 34032bbd7f73
Revises: 5f59903c42dc
Create Date: 2024-08-06 11:27:31.085154

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '34032bbd7f73'
down_revision = '5f59903c42dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.VARCHAR(),
                    type_=sa.LargeBinary(),
                    existing_comment='Зашифрованный пароль',
                    existing_nullable=False,
                    postgresql_using='hashed_password::bytea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.LargeBinary(),
                    type_=sa.VARCHAR(),
                    existing_comment='Зашифрованный пароль',
                    existing_nullable=False,
                    postgresql_using='hashed_password::varchar')
    # ### end Alembic commands ###
